apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: urlshortener
  labels:
    app: zookeeper
    tier: infrastructure
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: client
  - port: 2888
    targetPort: 2888
    protocol: TCP
    name: server
  - port: 3888
    targetPort: 3888
    protocol: TCP
    name: leader-election
  selector:
    app: zookeeper
