apiVersion: v1
kind: Service
metadata:
  name: url-service
  namespace: urlshortener
  labels:
    app: url-service
    tier: application
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: url-service
