apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: urlshortener

resources:
  - namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/name: url-shortener-platform
      app.kubernetes.io/version: "1.0.0"
