apiVersion: v1
kind: Namespace
metadata:
  name: urlshortener
  labels:
    name: urlshortener
    environment: production
    app.kubernetes.io/name: url-shortener-platform
    app.kubernetes.io/version: "1.0.0"
