apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets-dev.yaml
  - common-configmap.yaml
  - url-service-configmap.yaml
  - api-gateway-configmap.yaml
  - analytics-service-configmap.yaml
